#cau hinh ket noi db
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bookingdb
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Asia/Ho_Chi_Minh